using Blackbird.Applications.Sdk.Common.Dictionaries;
using Blackbird.Applications.Sdk.Common.Dynamic;

namespace Apps.Cohere.DataSourceHandlers
{
    public class TranslateLanguagesDataHandler : IStaticDataSourceItemHandler
    {
        public IEnumerable<DataSourceItem> GetData() => new List<DataSourceItem>
        {
            new("af", "Afrikaans"),
            new("am", "Amharic"),
            new("ar", "Arabic"),
            new("as", "Assamese"),
            new("az", "Azerbaijani"),
            new("be", "Belarusian"),
            new("bg", "Bulgarian"),
            new("bn", "Bengali"),
            new("bo", "Tibetan"),
            new("bs", "Bosnian"),
            new("ca", "Catalan"),
            new("ceb","Cebuano"),
            new("co", "Corsican"),
            new("cs", "Czech"),
            new("cy", "Welsh"),
            new("da", "Danish"),
            new("de", "German"),
            new("el", "Greek"),
            new("en", "English"),
            new("eo", "Esperanto"),
            new("es", "Spanish"),
            new("et", "Estonian"),
            new("eu", "Basque"),
            new("fa", "Persian"),
            new("fi", "Finnish"),
            new("fr", "French"),
            new("fy", "Frisian"),
            new("ga", "Irish"),
            new("gd", "Scots Gaelic"),
            new("gl", "Galician"),
            new("gu", "Gujarati"),
            new("ha", "Hausa"),
            new("haw","Hawaiian"),
            new("he", "Hebrew"),
            new("hi", "Hindi"),
            new("hmn","Hmong"),
            new("hr", "Croatian"),
            new("ht", "Haitian Creole"),
            new("hu", "Hungarian"),
            new("hy", "Armenian"),
            new("id", "Indonesian"),
            new("ig", "Igbo"),
            new("is", "Icelandic"),
            new("it", "Italian"),
            new("ja", "Japanese"),
            new("jv", "Javanese"),
            new("ka", "Georgian"),
            new("kk", "Kazakh"),
            new("km", "Khmer"),
            new("kn", "Kannada"),
            new("ko", "Korean"),
            new("ku", "Kurdish"),
            new("ky", "Kyrgyz"),
            new("la", "Latin"),
            new("lb", "Luxembourgish"),
            new("lo", "Laothian"),
            new("lt", "Lithuanian"),
            new("lv", "Latvian"),
            new("mg", "Malagasy"),
            new("mi", "Maori"),
            new("mk", "Macedonian"),
            new("ml", "Malayalam"),
            new("mn", "Mongolian"),
            new("mr", "Marathi"),
            new("ms", "Malay"),
            new("mt", "Maltese"),
            new("my", "Burmese"),
            new("ne", "Nepali"),
            new("nl", "Dutch"),
            new("no", "Norwegian"),
            new("ny", "Nyanja"),
            new("or", "Oriya"),
            new("pa", "Punjabi"),
            new("pl", "Polish"),
            new("pt", "Portuguese"),
            new("ro", "Romanian"),
            new("ru", "Russian"),
            new("rw", "Kinyarwanda"),
            new("si", "Sinhalese"),
            new("sk", "Slovak"),
            new("sl", "Slovenian"),
            new("sm", "Samoan"),
            new("sn", "Shona"),
            new("so", "Somali"),
            new("sq", "Albanian"),
            new("sr", "Serbian"),
            new("st", "Sesotho"),
            new("su", "Sundanese"),
            new("sv", "Swedish"),
            new("sw", "Swahili"),
            new("ta", "Tamil"),
            new("te", "Telugu"),
            new("tg", "Tajik"),
            new("th", "Thai"),
            new("tk", "Turkmen"),
            new("tl", "Tagalog"),
            new("tr", "Turkish"),
            new("tt", "Tatar"),
            new("ug", "Uighur"),
            new("uk", "Ukrainian"),
            new("ur", "Urdu"),
            new("uz", "Uzbek"),
            new("vi", "Vietnamese"),
            new("wo", "Wolof"),
            new("xh", "Xhosa"),
            new("yi", "Yiddish"),
            new("yo", "Yoruba"),
            new("zh", "Chinese"),
            new("zu", "Zulu"),
        };
    }
}
